{% set name = "libhiredis" %}
{% set version = "1.1.0" %}
{% set soversion = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/redis/hiredis/archive/v{{ version }}.tar.gz
  sha256: fe6d21741ec7f3fc9df409d921f47dfc73a4d8ff64f4ac6f1d95f951bf7f53d6
  patches:
    - hiredis-1.0.0-disable-network-tests.patch

build:
  number: 0
  skip: true  # [win and float(vc) < 14]
  run_exports:
    - {{ pin_subpackage('libhiredis', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}  # [not win]
    - cmake
    - make  # [unix]

  host:
    - msinttypes  # [win and float(vc) < 14]

test:
  commands:
    - ldd ${PREFIX}/lib/libhiredis.so  # [linux]
    - test -f ${PREFIX}/include/hiredis/hiredis.h  # [unix]
    - test -f ${PREFIX}/lib/libhiredis.{{ soversion }}${SHLIB_EXT}  # [osx]
    - if not exist %PREFIX%\\Library\\include\\hiredis\\hiredis.h exit 1  # [win]
    - echo "TODO - Pkg tests require redis server."

about:
  home: http://github.com/redis/hiredis
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Minimalistic C client for Redis >= 1.2

  dev_url: https://github.com/redis/hiredis

extra:
  recipe-maintainers:
    - sarnold
